FROM python:3.11-buster

WORKDIR /app

ADD . /app

RUN pip install --upgrade pip
RUN pip install -e .

RUN apt-get update -y && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

CMD ["python", "-m", "jonbot.__main__"]