FROM python:3.11

WORKDIR /app

ADD . /app

RUN pip install --upgrade pip
RUN pip install -e .


RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8091

CMD ["python", "-m", "jonbot.layer1_api_interface.api_main"]
