FROM python:3.11

WORKDIR /app

ADD . /app

RUN pip install --upgrade pip
RUN pip install -e .

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

CMD ["python", "-m", "jonbot.__main__", "bot_name"]
